mkcs:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: mkCloudStorage
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    database: 10
  minio:
    access-key: minioadmin
    secret-key: minioadmin
    endpoint: http://127.0.0.1:9000
    bucket-name: sky-take-out