mkcs:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: mkCloudStorage
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    database: 10
  minio:
    access-key: minioadmin
    secret-key: minioadmin
    endpoint: http://127.0.0.1:9000
    bucket-name: sky-take-out
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: 123456
    virtual-host: /
  mail:
    host: smtp.resend.com
    port: 587
    username: resend
    password: re_RHoMZKbQ_Cif3weqijmyykMtsok8iAnXf
    from: noreply@20051215.xyz
    from-name: MK Cloud Storage
